mode: deployment

nameOverride: ms-demo-otelcol

presets:
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true

config:
  exporters:
    otlp:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
    otlp/2:
      endpoint: "refinery.carefinery:4317"
      tls:
        insecure: true
      headers:
        "X-Honeycomb-Team": "REDACTED"

  processors:
    attributes:
      actions:
        - key: k8s.cluster.name
          value: cs-k8s-sandbox
          action: upsert
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [k8sattributes, attributes, memory_limiter, batch]
        exporters: [otlp, otlp/2]
